### ISSUE TITLE
Error with latest fabric release

### ISSUE THREAD

**Issue by pavog** [mactso/Regrowth#25]
**Fabric** Version: 1.18.2 (0.14.8)
Minecraft Version: 1.18.2 
WorldSeed: IDK
Regrowth version: [fabric-regrowth-1.18-0.30d.release.jar](https://www.curseforge.com/minecraft/mc-mods/regrowth/files/3826884)

**Describe the bug**
When I start the server it spams this message:
`at org.spongepowered.asm.mixin.transformer.ClassInfo.findSuperClass(ClassInfo.java:1426) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]`
and crashes (does not start).

**To Reproduce**
1. Create a new server
2. Download Fabric 1.18.2 (0.14.8)
3. Download Regrowth version Fabric 1.18 0.30d
4. Download the latest version of Fabric API for 1.18.2
5. Start the server
6. Wait a few seconds

**Expected behavior**
Not to crash

**Screenshots**
None

**Stack Trace** 

<details>
  <summary>Stack trace</summary>

```
[14:00:48] [main/INFO]: [STDOUT]: Register Regrowth Commands
[14:00:48] [main/INFO]: [STDOUT]: Exit Register
[14:00:48] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:00:48] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:00:48] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c018[49](https://aternos.org/log/#L49)e498]
[14:00:48] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498]
[14:00:48] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0]
[14:00:49] [main/WARN]: Failed to load datapacks, can't proceed with server load. You can either fix your datapacks or reset to vanilla with --safeMode
java.util.concurrent.ExecutionException: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3494$class_3495 failed
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.server.Main.main(Main.java:194) [server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3494$class_3495 failed
	at net.minecraft.class_3[50](https://aternos.org/log/#L50)3.method_18242(class_3503.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_3503.method_33176(class_3503.java:138) ~[server-intermediary.jar:?]
	at net.minecraft.class_3505.method_33181(class_3505.java:63) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?]
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3494$class_3495 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:419) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145) ~[fabric-loader-0.14.8.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:[52](https://aternos.org/log/#L52)0) ~[?:?]
	at net.minecraft.class_3503.method_18242(class_3503.java:112) ~[server-intermediary.jar:?]
	at net.minecraft.class_3503.method_33176(class_3503.java:138) ~[server-intermediary.jar:?]
	at net.minecraft.class_3505.method_33181(class_3505.java:63) ~[server-intermediary.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:16[55](https://aternos.org/log/#L55)) ~[?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1[62](https://aternos.org/log/#L62)2) ~[?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:1[65](https://aternos.org/log/#L65)) ~[?:?]
Caused by: java.lang.StackOverflowError
	at org.spongepowered.asm.mixin.transformer.ClassInfo.findSuperClass(ClassInfo.java:1421) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
```
</details>

**Full server log:**
https://mclo.gs/zzKS2kF

**Comment by mactso** [comment]
Thank you.  I appreciate your bug report!
I'll give this a look asap.
I only see warnings for regrowth in the log.
But it might be a regrowth mixin 
Did you run all the other mods without regrowth to isolate the error is only in regrowth?

We have about 3,000 downloads without error reports and tested it locally without an issue so trying to isolate the problem,

Thanks,
Much Appreciated.  
Two Guys,
MacTso

**Comment by pavog** [comment]
Mhm, I don't know what I did wrong on the first try, but yeah it seems to work now.
