### ISSUE TITLE
fabric server for 1.19.3 throws error when trying to install this mod

### ISSUE THREAD

**Issue by graven04** [mactso/Regrowth#43]
Forge Version : fabric
Minecraft Version: 1.19.3
WorldSeed: 

**Describe the bug**

**To Reproduce**

**Error**
[20:48:35] [main/INFO]: Config 'regrowthconfig' is missing, generating default one...
[20:48:35] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'regrowth'!
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.17.jar:?]
        at net.minecraft.server.Main.main(Main.java:102) ~[server-intermediary.jar:?]
        at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.17.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.19.3-loader.0.14.17-launcher.0.11.2.jar:0.11.2]
Caused by: java.lang.NoSuchFieldError: field_11146
        at com.mactso.regrowth.config.MyConfig.assignConfigs(MyConfig.java:178) ~[fabric-release-regrowth-1.19-31.1.0.jar:?]
        at com.mactso.regrowth.config.MyConfig.registerConfigs(MyConfig.java:146) ~[fabric-release-regrowth-1.19-31.1.0.jar:?]
        at com.mactso.regrowth.Main.onInitialize(Main.java:33) ~[fabric-release-regrowth-1.19-31.1.0.jar:?]
        at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.17.jar:?]
        ... 8 more

**Expected behavior**
works without errors

**Desktop (please complete the following information):**
 - OS: linux

**Comment by graven04** [comment]
It seems I am using the wrong jar file. Sorry. Closing this issue. Maybe it should state this clearly on description instead of the chats.

**Comment by mactso** [comment]
Thanks!  I was traveling for the last week.

I see that I haven't done a 1.19.3 version for this yet.    There may only be a 1.19.4 version since it is out already.
I'll try to label these better.   If you go into the curseforge page it shows the versions but that's hidden from view on the main page.

**Comment by mactso** [comment]
Hi.  they had renamed the registries and moved the biometags.
this is fixed and i'm submitting 1.19.3 version for approval now.
