### ISSUE TITLE
Crash?

### ISSUE THREAD

**Issue by talhanation** [mactso/Regrowth#7]
Forge Version : 35.1.13
Minecraft Version: 1.16.4
WorldSeed: -

**Describe the bug**
Its a crash, it could be not compatible with a other mod (i think its guard villagers)

**To Reproduce**
1. Join a world

crashlog:
---- Minecraft Crash Report ----
// Daisy, daisy...

Time: 23.12.20 12:58
Description: Ticking entity

java.lang.NoSuchFieldError: STONE
	at com.mactso.regrowth.events.MoveEntityEvent.doMobRegrowthEvents(MoveEntityEvent.java:239) ~[?:1.108.0.17] {re:classloading}
	at com.mactso.regrowth.events.MoveEntityEvent.doEntityMove(MoveEntityEvent.java:176) ~[?:1.108.0.17] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_155_MoveEntityEvent_doEntityMove_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,xf:fml:b3m:core_transformer,re:mixin}
	at net.minecraft.world.server.ServerWorld$$Lambda$7239/1522189143.accept(Unknown Source) ~[?:?] {}
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:b3m:core_transformer,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,xf:fml:b3m:core_transformer,re:mixin}
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6673/1481851679.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at com.mactso.regrowth.events.MoveEntityEvent.doMobRegrowthEvents(MoveEntityEvent.java:239) ~[?:1.108.0.17] {re:classloading}
	at com.mactso.regrowth.events.MoveEntityEvent.doEntityMove(MoveEntityEvent.java:176) ~[?:1.108.0.17] {re:classloading}
	at net.minecraftforge.eventbus.ASMEventHandler_155_MoveEntityEvent_doEntityMove_LivingUpdateEvent.invoke(.dynamic) ~[?:?] {}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?] {}
	at net.minecraftforge.common.ForgeHooks.onLivingUpdate(ForgeHooks.java:315) ~[?:?] {re:classloading,re:mixin}
	at net.minecraft.entity.LivingEntity.func_70071_h_(LivingEntity.java:2112) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityMixin,pl:mixin:APP:spiderstpo.mixins.json:LivingEntityClientMixin,pl:mixin:A}
	at net.minecraft.entity.MobEntity.func_70071_h_(MobEntity.java:430) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:spiderstpo.mixins.json:MobEntityMixin,pl:mixin:A}
	at net.minecraft.world.server.ServerWorld.func_217479_a(ServerWorld.java:611) ~[?:?] {re:classloading,xf:fml:b3m:core_transformer,re:mixin}
	at net.minecraft.world.server.ServerWorld$$Lambda$7239/1522189143.accept(Unknown Source) ~[?:?] {}
-- Entity being ticked --
Details:
	Entity Type: minecraft:skeleton (net.minecraft.entity.monster.SkeletonEntity)
	Entity ID: 306
	Entity Name: Skeleton
	Entity's Exact location: -4471.50, 49.00, 2352.50
	Entity's Block location: World: (-4472,49,2352), Chunk: (at 8,3,0 in -280,147; contains blocks -4480,0,2352 to -4465,255,2367), Region: (-9,4; contains chunks -288,128 to -257,159, blocks -4608,0,2048 to -4097,255,2559)
	Entity's Momentum: 0.00, -0.08, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_217390_a(World.java:554) ~[?:?] {re:classloading,pl:accesstransformer:B,xf:fml:b3m:core_transformer,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:404) ~[?:?] {re:classloading,xf:fml:b3m:core_transformer,re:mixin}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['talhanation'/255, l='ServerLevel[The New World]', x=-4472.50, y=84.00, z=2416.50]]
	Chunk stats: ServerChunkCache: 2599
	Level dimension: minecraft:overworld
	Level spawn location: World: (-4464,85,2420), Chunk: (at 0,5,4 in -279,151; contains blocks -4464,0,2416 to -4449,255,2431), Region: (-9,4; contains chunks -288,128 to -257,159, blocks -4608,0,2048 to -4097,255,2559)
	Level time: 51 game time, 938 day time
	Level name: The New World
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true
	Level weather: Rain time: 129166 (now: false), thunder time: 23644 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:850) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:786) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:118) ~[?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:641) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) [?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer$$Lambda$6673/1481851679.run(Unknown Source) [?:?] {}
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_51] {}

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3259023552 bytes (3108 MB) / 4731174912 bytes (4512 MB) up to 6442450944 bytes (6144 MB)
	CPUs: 4
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.6+85+master.325de55
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-3.0.5-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.4-35.1.13.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/OptiFine_1.16.4_HD_U_G5.jar OptiFine TRANSFORMATIONSERVICE 
		/forge-1.16.4-35.1.13.jar fml TRANSFORMATIONSERVICE 
	FML: 35.1
	Forge: net.minecraftforge:35.1.13
	FML Language Providers: 
		javafml@35.1
		minecraft@1
	Mod List: 
		forge-1.16.4-35.1.13-client.jar                   |Minecraft                     |minecraft                     |1.16.4              |DONE      |NOSIGNATURE
		wt_improvements-1.16.3-1.1.0.0.jar                |Wandering Trader Improvements |wt_improvements               |1.16.3-1.1.0.0      |DONE      |NOSIGNATURE
		tetra-1.16.3-3.3.0.jar                            |Tetra                         |tetra                         |3.3.0               |DONE      |NOSIGNATURE
		Tabula-1.16.3-10.0.0.jar                          |Tabula                        |tabula                        |10.0.0              |DONE      |NOSIGNATURE
		Camels-1.16.4-1.0.0.jar                           |Camels Mod                    |camels                        |1.0.0               |DONE      |NOSIGNATURE
		AmbientSounds_v3.1.1_mc1.16.3.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |NOSIGNATURE
		zombiehs_1.16.3-2.5.jar                           |Zombie Horse Spawn            |zombiehs                      |2.5                 |DONE      |NOSIGNATURE
		spiders-2.0-1.16.3-1.0.4.jar                      |Spiders 2.0                   |spiderstpo                    |1.0.4               |DONE      |NOSIGNATURE
		CreativeCore_v2.0.7_mc1.16.2.jar                  |CreativeCore                  |creativecore                  |2.0.0               |DONE      |NOSIGNATURE
		extratrades-1.16.3-1.1.jar                        |Extra Trades                  |extratrades                   |1.16.3-1.1          |DONE      |NOSIGNATURE
		FallingTree-Forge-1.16.3-2.7.0.jar                |Falling Tree                  |falling_tree                  |2.7.0               |DONE      |NOSIGNATURE
		astikorcarts-1.16.4-1.1.0.jar                     |AstikorCarts                  |astikorcarts                  |1.1.0               |DONE      |NOSIGNATURE
		villagernames_1.16.3-2.5.jar                      |Villager Names                |villagernames                 |2.5                 |DONE      |NOSIGNATURE
		TerraForged-1.16.4-0.2.0-ALPHA-3.jar              |TerraForged                   |terraforged                   |0.2.0-ALPHA-3       |DONE      |NOSIGNATURE
		realisticbees_1.16.3-1.0.jar                      |Realistic Bees                |realisticbees                 |1.0                 |DONE      |NOSIGNATURE
		collective-1.16.3-1.53.jar                        |Collective                    |collective                    |1.53                |DONE      |NOSIGNATURE
		mgui-1.16.3-3.1.2.jar                             |mgui                          |mgui                          |3.1.2               |DONE      |NOSIGNATURE
		citadel-1.5.3.jar                                 |Citadel                       |citadel                       |1.5.3               |DONE      |NOSIGNATURE
		alexsmobs-1.1.1.jar                               |Alex's Mobs                   |alexsmobs                     |1.1.1               |DONE      |NOSIGNATURE
		betteranimals-1.16.4-5.4.0.jar                    |Cyber's Better Animal Models  |betteranimals                 |5.4.0               |DONE      |NOSIGNATURE
		Regrowth-1.16.1-1.108.0.17.jar                    |Regrowth Mod                  |regrowth                      |1.108.0.17          |DONE      |NOSIGNATURE
		illagersweararmor-1.0.3.jar                       |Illagers Wear Armor           |illagersweararmor             |1.0.3               |DONE      |NOSIGNATURE
		guardvillagers-1.16.4-1.1.7.jar                   |Guard Villagers               |guardvillagers                |1.1.7               |DONE      |NOSIGNATURE
		hunterillager-1.16.3-1.1.3.jar                    |HunterIllager                 |hunterillager                 |1.16.3-1.1.3        |DONE      |NOSIGNATURE
		AI-Improvements-1.16.2-0.3.0.jar                  |AI-Improvements               |aiimprovements                |0.3.0               |DONE      |NOSIGNATURE
		spidersprwebs_1.16.3_1.1.jar                      |Spiders Produce Webs          |spidersprwebs                 |1.1                 |DONE      |NOSIGNATURE
		iChunUtil-1.16.3-10.0.0.jar                       |iChunUtil                     |ichunutil                     |10.0.0              |DONE      |NOSIGNATURE
		custom-crosshair-mod-v1.0.3-forge-mc1.16.3.jar    |Custom Crosshair Mod          |custom-crosshair-mod          |1.0.3               |DONE      |NOSIGNATURE
		BetterBurning-1.16.3-4.0.2.jar                    |BetterBurning                 |betterburning                 |4.0.2               |DONE      |NOSIGNATURE
		forge-1.16.4-35.1.13-universal.jar                |Forge                         |forge                         |35.1.13             |DONE      |22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		Waddles-1.16.3-0.8.9.jar                          |Waddles                       |waddles                       |1.16.3-0.8.9        |DONE      |NOSIGNATURE
		playereatinganimation-1.2.jar                     |Player Eating Animation       |playereatinganimation         |1.2                 |DONE      |NOSIGNATURE
		B3M-1.16.4-02.jar                                 |Вращение Земли Майнкрафт      |b3m                           |1.16.4-02           |DONE      |NOSIGNATURE
		villagerdeathm_1.16.3_1.5.jar                     |Villager Death Messages       |villagerdeathm                |1.5                 |DONE      |NOSIGNATURE
	Crash Report UUID: 39329750-322f-4576-89ff-20986b3e71fa
	Player Count: 1 / 8; [ServerPlayerEntity['talhanation'/255, l='ServerLevel[The New World]', x=-4472.50, y=84.00, z=2416.50]]
	Data Packs: vanilla, mod:wt_improvements (incompatible), mod:tetra, mod:tabula, mod:camels (incompatible), mod:ambientsounds (incompatible), mod:zombiehs, mod:spiderstpo, mod:creativecore (incompatible), mod:extratrades (incompatible), mod:falling_tree, mod:astikorcarts, mod:villagernames, mod:terraforged (incompatible), mod:realisticbees, mod:collective, mod:mgui (incompatible), mod:citadel (incompatible), mod:alexsmobs, mod:betteranimals (incompatible), mod:illagersweararmor (incompatible), mod:guardvillagers, mod:hunterillager, mod:aiimprovements, mod:spidersprwebs, mod:ichunutil, mod:custom-crosshair-mod, mod:betterburning, mod:forge, mod:waddles, mod:b3m (incompatible), mod:villagerdeathm, mod:regrowth (incompatible), mod:playereatinganimation (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Render Distance Chunks: 32
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 456.71
	OpenGlRenderer: GeForce GTX 1060 6GB/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 4

**Comment by mactso** [comment]
Hi! Thanks for the crash report.
You resolved this by using version 1.16.3/4 instead of version 1.16.1.

Curseforge only lists the last update.  I'm going to make some cleanup changes and changes to the gradle setup so I can push a 1.16.4 version as the "most current version" so other users don't have this problem.
